<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\MediaRepresentation $media
 * @var array $options
 */

$assetUrl = $this->plugin('assetUrl');

$this->headLink()->appendStylesheet($assetUrl('vendor/pdf.js/web/pdf_viewer.css', 'SimplePdf'));
$this->headLink()->appendStylesheet($assetUrl('css/simplepdf.css', 'SimplePdf'));

$basePath = $assetUrl('', 'SimplePdf', false, false) . 'vendor/pdf.js/';
$basePath = json_encode($basePath, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
$defaultUrl = json_encode($media->originalUrl(), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

$this->headScript()->appendScript(
    'const BASE_PATH = ' . $basePath . '; const DEFAULT_URL = ' . $defaultUrl . ';');
$this->headScript()->appendFile($assetUrl('vendor/pdf.js/build/pdf.min.js', 'SimplePdf'));
$this->headScript()->appendFile($assetUrl('vendor/pdf.js/web/pdf_viewer.js', 'SimplePdf'));
$this->headScript()->appendFile($assetUrl('js/simplepdf.js', 'SimplePdf'), 'text/javascript', ['defer' => 'defer']);

?>
<div id="pdf-controls" role="toolbar" aria-label="<?= $this->translate('PDF viewer controls') ?>">
    <div>
        <input title="<?= $this->translate('Page number') ?>" type="number" value="1" min="1" max="1" id="pdf-page-num">
        <span id="pdf-page-count"><?= $this->translate('of') ?> 1</span>
    </div>
    <div>
        <button title="<?= $this->translate('Zoom in') ?>" id="pdf-zoom-in">
            <span class="fa fa-search-plus" aria-hidden="true"></span>
        </button>
        <button title="<?= $this->translate('Zoom out') ?>" id="pdf-zoom-out">
            <span class="fa fa-search-minus" aria-hidden="true"></span>
        </button>
        <button title="<?= $this->translate('Fit to page') ?>" id="pdf-zoom-fit">
            <span class="fa fa-expand" aria-hidden="true"></span>
        </button>
    </div>
</div>
<div id="pdf-container">
    <div id="pdfjs-container" role="document" aria-label="<?= $this->translate('PDF content') ?>">
        <div id="viewer" class="pdfViewer"></div>
    </div>
</div>